### Buscar todos os contratos
GET http://localhost:8080/api/v1/contratos

### Buscar contrato pelo ID
GET http://localhost:8080/api/v1/contratos/1

### Inserir uma novo contrato
POST http://localhost:8080/api/v1/contratos
Content-Type: application/json

{
    "numeroContrato": "5",
    "dataInicio": "2022-01-01",
    "dataValidade": "2024-01-01",
    "valor": 1000,
    "contratente": "Univille",
    "contratado": "TESTE CRUDE ADD"
}

### Atualizar a contrato
PUT http://localhost:8080/api/v1/contratos/f0ae38b7-8a8c-48e7-bc23-6a0c82a2f4c3
Content-Type: application/json

{
    "numeroContrato": "6",
    "dataInicio": "2022-01-01",
    "dataValidade": "2024-01-01",
    "valor": 1000,
    "contratente": "Univille",
    "contratado": "TESTE CRUDE ALTERAR"
}

### Remover a contrato
DELETE  http://localhost:8080/api/v1/contratos/f0ae38b7-8a8c-48e7-bc23-6a0c82a2f4c3
Content-Type: application/json