### Buscar todos os contratos
GET http://localhost:8080/api/v1/contratos

### Buscar contrato pelo ID
GET http://localhost:8080/api/v1/contrato/1

### Inserir uma novo contrato
POST http://localhost:8080/api/v1/contrato
Content-Type: application/json

{
    "id": "5",
    "numeroContrato": "5",
    "dataInicio": "2022-01-01",
    "dataValidade": "2024-01-01",
    "valor": 1000,
    "contratente": "Univille",
    "contratado": "TESTE CRUDE ADD"
}

### Atualizar a contrato
PUT http://localhost:8080/api/v1/grades/1c43c274-f7dd-4647-a446-e270787fb1bc

{
    "id": "5",
    "numeroContrato": "5",
    "dataInicio": "2022-01-01",
    "dataValidade": "2024-01-01",
    "valor": 1000,
    "contratente": "Univille",
    "contratado": "TESTE CRUDE ALTERAR"
}

### Remover a contrato
DELETE  http://localhost:8080/api/v1/contrato/5
Content-Type: application/json