### Buscar todos os contratos
GET http://localhost:8080/api/v1/contratos

### Buscar contrato pelo ID
GET http://localhost:8080/api/v1/contratos/df0565d0-af4f-4f5e-813a-0b483d242de7

### Inserir uma novo contrato
POST http://localhost:8080/api/v1/contratos
Content-Type: application/json

{
    "numeroContrato": "10",
    "dataInicio": "2022-01-01",
    "dataValidade": "2024-01-01",
    "valor": 9000,
    "contratente": "Univille",
    "contratado": "Luizinho"
}

### Atualizar a contrato
### !!! FECHAR O POSTMAN E ABRIR NOVAMENTE PARA ATUALIZAR O HEADER !!!
PUT http://localhost:8080/api/v1/contratos/df0565d0-af4f-4f5e-813a-0b483d242de7
Content-Type: application/json

{
    "numeroContrato": "10",
    "dataInicio": "2022-01-01",
    "dataValidade": "2024-01-01",
    "valor": 1000,
    "contratente": "Univille",
    "contratado": "TESTE CRUDE ALTERAR"
}

### Remover a contrato
### !!! FECHAR O POSTMAN E ABRIR NOVAMENTE PARA ATUALIZAR O HEADER !!!
DELETE  http://localhost:8080/api/v1/contratos/df0565d0-af4f-4f5e-813a-0b483d242de7
Content-Type: application/json